name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Visual Studio shell
      # You may pin to the exact commit or the version.
      # uses: egor-tensin/vs-shell@2cef0a902be6c2434178a0d0e4d83ae07a9dd0e0
      uses: egor-tensin/vs-shell@v2
      with:
        # Target architecture
        arch: x64 # optional, default is x64
    - name: Build
      run: msbuild "Minecraft Multiple Command Combiner/Minecraft Multiple Command Combiner.csproj"
    - uses: actions/upload-artifact@v2
      with:
        name: Output
        path: / # or path/to/artifact
